### ISSUE TITLE
Please tag a release for the Library manager. 

### ISSUE THREAD

**Issue by photodude** [VincentLim/TimerFour#1]
Please create a release or tag that matches the version value in your library.properties file.

Doing so will allow Arduino to proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

An open issue requesting your library be added to the index. 
https://github.com/arduino/Arduino/issues/8758

Thank you for creating this modification.

**Comment by VincentLim** [comment]
Hi, 

Done.

I didn't read the FAQ, let me know if further steps are needed.
Please also note I used this lib only for 'home' project and so, it is quite untested.

**Comment by photodude** [comment]
@VincentLim Thank you. This has been added now to the Arduino Library manager.
